@api = http://localhost:3000/tasks

GET {{api}}

###
GET {{api}}/31

###
GET {{api}}/count

###
POST {{api}}
Content-Type: application/json

{
    "title": "task444",
    "description": "some description 4" 
}

###
DELETE {{api}}/31

###
PUT {{api}}/27
Content-Type: application/json

{
    "title": "Dormir",
    "description": "update" 
}